apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
