version: '3'
services:
  rabbit:
    image: rabbitmq:latest
    env_file: .env
    ports:
      - 5672:5672
  nlp:
    build: nlp
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./nlp:/app
    ports:
      - 5000:5000
  server:
    image: yarnpkg/dev
    command: ['yarn', 'dev']
    env_file: .env
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
  postgres:
    image: postgres:10.3
    restart: always
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres: ~
