version: '3'
services:
  server:
    image: yarnpkg/dev
    command: ['yarn', 'dev']
    env_file: .env
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mongo
            uri: "mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo"
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~