apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: rabbit
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: env
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: env
              key: RABBITMQ_DEFAULT_PASS
        image: rabbitmq:3.7
        name: rabbit
        ports:
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
status: {}
